//import com.thedesignerx.saim.new_message_app.ApiClient.apiInterface
//import com.thedesignerx.saim.new_message_app.ApiClient.apiInterfaceRegister
//import androidx.appcompat.app.AppCompatActivity
//import android.widget.TextView
//import android.widget.EditText
//import android.os.Bundle
//import com.thedesignerx.saim.new_message_app.R
//import android.text.TextUtils
//import android.widget.Toast
//import com.thedesignerx.saim.new_message_app.LoginRequest
//import com.thedesignerx.saim.new_message_app.LoginResponse
//import com.thedesignerx.saim.new_message_app.ApiClient
//import android.content.Intent
//import com.thedesignerx.saim.new_message_app.register
//import com.thedesignerx.saim.new_message_app.RegistrationsRequest
//import com.thedesignerx.saim.new_message_app.RegistrationsResponse
//import retrofit2.http.POST
//import android.app.Activity
//import android.widget.ImageButton
//import com.thedesignerx.saim.new_message_app.MainActivity
//import android.app.PendingIntent
//import android.os.AsyncTask